// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
)

func Examples() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"max-w-4xl w-full space-y-12 p-4 sm:p-8\"><header class=\"text-center\"><h1 class=\"text-4xl font-bold mb-2\"><span class=\"text-yellow-500\">GOAT</span> Stack Examples</h1><p class=\"text-lg mb-6 max-w-xl mx-auto\">Explore the power of Alpine.js and Tailwind CSS with these interactive examples</p></header><section class=\"space-y-8\"><h2 class=\"text-2xl font-semibold mb-4\">Basic Counter</h2><div class=\"border border-current p-6 rounded-lg\" x-data=\"{ count: 0 }\"><p class=\"mb-4\">Current count: <span x-text=\"count\" class=\"font-bold text-yellow-500\"></span></p><button @click=\"count++\" class=\"border border-current px-4 py-2 rounded-md hover:bg-stone-100 dark:hover:bg-stone-800 transition\">Increment</button></div><div class=\"relative\" x-data=\"{ copied: false }\"><pre class=\"bg-stone-100 dark:bg-stone-800 p-4 rounded-md overflow-x-auto\"><code class=\"text-yellow-500\" x-ref=\"codeBlockCounter\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("<div x-data=\"{ count: 0 }\">\\n  <p>Current count: <span x-text=\"count\"></span></p>\\n  <button @click=\"count++\">Increment</button>\\n</div>"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/Examples.templ`, Line: 21, Col: 308}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</code></pre><button @click=\"navigator.clipboard.writeText($refs.codeBlockCounter.textContent.trim()); copied = true; setTimeout(() =&gt; copied = false, 2000)\" class=\"absolute top-2 right-2 bg-stone-200 dark:bg-stone-700 p-1 rounded-md hover:bg-stone-300 dark:hover:bg-stone-600 transition\" :aria-label=\"copied ? &#39;Copied!&#39; : &#39;Copy to clipboard&#39;\"><span x-show=\"!copied\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = IconCopy().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <span x-show=\"copied\" class=\"text-green-500\">✓</span></button></div></section><section class=\"space-y-8\"><h2 class=\"text-2xl font-semibold mb-4\">Toggle Visibility</h2><div class=\"border border-current p-6 rounded-lg\" x-data=\"{ show: false }\"><button @click=\"show = !show\" class=\"border border-current px-4 py-2 rounded-md hover:bg-stone-100 dark:hover:bg-stone-800 transition mb-4\">Toggle Content</button><p x-show=\"show\" x-transition class=\"bg-stone-100 dark:bg-stone-800 p-4 rounded-md\">This content can be toggled!</p></div><div class=\"relative\" x-data=\"{ copied: false }\"><pre class=\"bg-stone-100 dark:bg-stone-800 p-4 rounded-md overflow-x-auto\"><code class=\"text-yellow-500\" x-ref=\"codeBlockToggle\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("<div x-data=\"{ show: false }\">\\n  <button @click=\"show = !show\">Toggle Content</button>\\n  <p x-show=\"show\" x-transition>This content can be toggled!</p>\\n</div>"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/Examples.templ`, Line: 41, Col: 332}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</code></pre><button @click=\"navigator.clipboard.writeText($refs.codeBlockToggle.textContent.trim()); copied = true; setTimeout(() =&gt; copied = false, 2000)\" class=\"absolute top-2 right-2 bg-stone-200 dark:bg-stone-700 p-1 rounded-md hover:bg-stone-300 dark:hover:bg-stone-600 transition\" :aria-label=\"copied ? &#39;Copied!&#39; : &#39;Copy to clipboard&#39;\"><span x-show=\"!copied\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = IconCopy().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <span x-show=\"copied\" class=\"text-green-500\">✓</span></button></div></section><section class=\"space-y-8\"><h2 class=\"text-2xl font-semibold mb-4\">Two-way Binding</h2><div class=\"border border-current p-6 rounded-lg\" x-data=\"{ name: &#39;&#39; }\"><input type=\"text\" x-model=\"name\" placeholder=\"Enter your name\" class=\"w-full p-2 rounded-md mb-4 bg-stone-100 dark:bg-stone-800\"><p>Hello, <span x-text=\"name || &#39;stranger&#39;\" class=\"font-bold text-yellow-500\"></span>!</p></div><div class=\"relative\" x-data=\"{ copied: false }\"><pre class=\"bg-stone-100 dark:bg-stone-800 p-4 rounded-md overflow-x-auto\"><code class=\"text-yellow-500\" x-ref=\"codeBlockBinding\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("<div x-data=\"{ name: '' }\">\\n  <input type=\"text\" x-model=\"name\" placeholder=\"Enter your name\">\\n  <p>Hello, <span x-text=\"name || 'stranger'\"></span>!</p>\\n</div>"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/Examples.templ`, Line: 61, Col: 339}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</code></pre><button @click=\"navigator.clipboard.writeText($refs.codeBlockBinding.textContent.trim()); copied = true; setTimeout(() =&gt; copied = false, 2000)\" class=\"absolute top-2 right-2 bg-stone-200 dark:bg-stone-700 p-1 rounded-md hover:bg-stone-300 dark:hover:bg-stone-600 transition\" :aria-label=\"copied ? &#39;Copied!&#39; : &#39;Copy to clipboard&#39;\"><span x-show=\"!copied\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = IconCopy().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <span x-show=\"copied\" class=\"text-green-500\">✓</span></button></div></section><section class=\"space-y-8\"><h2 class=\"text-2xl font-semibold mb-4\">Conditional Styling</h2><div class=\"border border-current p-6 rounded-lg\" x-data=\"{ count: 0 }\"><p class=\"mb-4\">Count: <span x-text=\"count\" :class=\"{ &#39;text-green-500&#39;: count &gt; 0, &#39;text-red-500&#39;: count &lt; 0 }\" class=\"font-bold\"></span></p><button @click=\"count++\" class=\"border border-current px-4 py-2 rounded-md hover:bg-stone-100 dark:hover:bg-stone-800 transition mr-2\">Increment</button> <button @click=\"count--\" class=\"border border-current px-4 py-2 rounded-md hover:bg-stone-100 dark:hover:bg-stone-800 transition\">Decrement</button></div><div class=\"relative\" x-data=\"{ copied: false }\"><pre class=\"bg-stone-100 dark:bg-stone-800 p-4 rounded-md overflow-x-auto\"><code class=\"text-yellow-500\" x-ref=\"codeBlockStyling\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("<div x-data=\"{ count: 0 }\">\\n  <p>Count: <span x-text=\"count\" :class=\"{ 'text-green-500': count > 0, 'text-red-500': count < 0 }\"></span></p>\\n  <button @click=\"count++\">Increment</button>\\n  <button @click=\"count--\">Decrement</button>\\n</div>"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/Examples.templ`, Line: 82, Col: 420}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</code></pre><button @click=\"navigator.clipboard.writeText($refs.codeBlockStyling.textContent.trim()); copied = true; setTimeout(() =&gt; copied = false, 2000)\" class=\"absolute top-2 right-2 bg-stone-200 dark:bg-stone-700 p-1 rounded-md hover:bg-stone-300 dark:hover:bg-stone-600 transition\" :aria-label=\"copied ? &#39;Copied!&#39; : &#39;Copy to clipboard&#39;\"><span x-show=\"!copied\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = IconCopy().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <span x-show=\"copied\" class=\"text-green-500\">✓</span></button></div></section><section class=\"space-y-8\"><h2 class=\"text-2xl font-semibold mb-4\">Loading State</h2><div class=\"border border-current p-6 rounded-lg\" x-data=\"{ loading: false }\"><button @click=\"loading = true; setTimeout(() =&gt; loading = false, 2000)\" class=\"border border-current px-4 py-2 rounded-md hover:bg-stone-100 dark:hover:bg-stone-800 transition\" :disabled=\"loading\"><span x-show=\"!loading\">Click me</span> <span x-show=\"loading\" class=\"inline-flex items-center\"><svg class=\"animate-spin -ml-1 mr-3 h-5 w-5 text-yellow-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\"><circle class=\"opacity-25\" cx=\"12\" cy=\"12\" r=\"10\" stroke=\"currentColor\" stroke-width=\"4\"></circle> <path class=\"opacity-75\" fill=\"currentColor\" d=\"M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z\"></path></svg> Loading...</span></button></div><div class=\"relative\" x-data=\"{ copied: false }\"><pre class=\"bg-stone-100 dark:bg-stone-800 p-4 rounded-md overflow-x-auto\"><code class=\"text-yellow-500\" x-ref=\"codeBlockLoading\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("<div x-data=\"{ loading: false }\">\\n  <button @click=\"loading = true; setTimeout(() => loading = false, 2000)\" :disabled=\"loading\">\\n    <span x-show=\"!loading\">Click me</span>\\n    <span x-show=\"loading\">\\n      <!-- Loading spinner SVG -->\\n      Loading...\\n    </span>\\n  </button>\\n</div>"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/Examples.templ`, Line: 110, Col: 473}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</code></pre><button @click=\"navigator.clipboard.writeText($refs.codeBlockLoading.textContent.trim()); copied = true; setTimeout(() =&gt; copied = false, 2000)\" class=\"absolute top-2 right-2 bg-stone-200 dark:bg-stone-700 p-1 rounded-md hover:bg-stone-300 dark:hover:bg-stone-600 transition\" :aria-label=\"copied ? &#39;Copied!&#39; : &#39;Copy to clipboard&#39;\"><span x-show=\"!copied\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = IconCopy().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <span x-show=\"copied\" class=\"text-green-500\">✓</span></button></div></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
